### ISSUE TITLE
Can't use GearmanClient from same directory as gearman.py

### ISSUE THREAD

**Issue by jonasvp** [fwenzel/django-gearman#4]
Hi,

thanks for django-gearman! I ran into an issue and I'm wondering how you would solve it: in one application directory, I have a background job defined in gearman.py while from my model's save method (in models.py) I want to dispatch a background task.

Now, when I try to do an "from gearman import GearmanClient" in models.py I get a NameError because Python looks in gearman.py from my application directory instead of the gearman module installed site-wide. Have you run into this issue? I solved it by forking django-gearman and renaming gearman.py to gearjobs.py (gearman_jobs is taken as well). Is there a better way?

Cheers,

  Jonas

**Comment by fwenzel** [comment]
Hi Jonas, glad you like django-gearman. I think it's generally a bad idea to make local modules that have the same name as global modules you want to import. This way you are masking the global namespace by overwriting names locally, which is bad style. I notice that I've enabled this very behavior, which I should definitely change!

Thank you for the heads-up. I'll probably rename it to gearman_jobs, and replace the global job list with a different name. If you make a patch for that, I'll of course gladly pull.

**Comment by jonasvp** [comment]
Hi Fred, thanks for the quick feedback. Pull request coming through...

**Comment by fwenzel** [comment]
I landed your code and incremented the version number. Thanks again!
